apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-service-config
data:
  PORT: "3003"
  NODE_ENV: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "eventbooking"
  DB_SCHEMA: "booking_service"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  NATS_URL: "nats://nats:4222"
  NATS_BOOKING_SUBJECT: "booking.confirmed"
  USER_SERVICE_URL: "http://user-service:3001"
  EVENT_SERVICE_URL: "http://event-service:3002"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"

